# Generated by Django 5.2 on 2025-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
