# Generated by Django 5.2 on 2025-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0002_message_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slack_ts',
            field=models.CharField(max_length=100),
        ),
    ]
