services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dlp_db
      MYSQL_USER: dlp_user
      MYSQL_PASSWORD: dlp_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"
 
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    command: ["uvicorn", "cp_project.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  dlp_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ~/.aws:/root/.aws:ro
    command: python dlp_consumer/run_consumer.py
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
