version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dlp_db
      MYSQL_USER: dlp_user
      MYSQL_PASSWORD: dlp_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"
 
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  dlp_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: python dlp_consumer/run_consumer.py
    depends_on:
      - web

volumes:
  db_data:
